config/routes.rb
Ck::Application.routes.draw do

  root :to => "pages#index"
  
  match 'mailer(/:action(/:id(.:format)))' => 'mailer#:action'
  match "follows/multi_create_new" => "follows#multi_create", :as => :multi_create_follows
  match "follows/create_new" => "follows#create_new", :as => :create_follow
  match "/signup" => "users#new"
  match "/login" => "sessions#new", :as => "login"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/pricing" => "pages#pricing"
  match "/demo" => "pages#demo"
  match "/learn" => "pages#learn"
  match "/about" => "pages#about"
  match "/bad_words" => "pages#bad_words"
  match "/team" => "pages#team"
  match "/guidelines" => "pages#guidelines"
  match "/help" => "pages#help"
  match "/contact" => "pages#contact"
  match "/founder_signout" => "shells#destroy"
  match "/invite_coworkers" => "pages#invite_coworkers"
  match "/invite_others" => "pages#invite_others"
  match "/admin" => "admin#index", :as => :admin
  
  match "compliments/set_compliment_types" => "compliments#set_compliment_types"
  match "/email_api/new_account_confirmation" => "email_api#new_account_confirmation",
        :as => :new_account_confirmation
  match "/email_api/new_email_confirmation" => "email_api#new_email_confirmation",
        :as => :new_email_confirmation
  match "/email_api/invitation_acceptance" => "email_api#invitation_acceptance",
        :as => :invitation_acceptance
  match "/email_api/compliment_new" => "email_api#compliment_new",
        :as => :compliment_new_user
  match "/email_api/accept_compliment" => "email_api#accept_compliment",
        :as => :accept_compliment
  match "/email_api/decline_compliment" => "email_api#decline_compliment",
        :as => :decline_compliment
  match "/recognitions/:recognition_type_id/:recognition_id" => "recognitions#show", 
        :as => :show_recognition
  match "/relationships/:id/accept" => "relationships#accept", :as => :accept_relationship
  match "/relationships/:id/decline" => "relationships#decline", :as => :decline_relationship
  match "/rewards/add_to_cart" => "rewards#add_to_cart"
  match "/rewards/filter_rewards_results" => "rewards#filter_rewards_results"
  match "/rewards/cart" => "rewards#cart", :as => :cart
  match "/rewards/checkout" => "rewards#checkout", :as => :checkout
  match "/rewards/remove_from_cart" => "rewards#remove_from_cart", :as => :remove_from_cart
  match "/search/skills" => "search#skills"
  match "/search/site" => "search#site"
  match "/search/compliment_receiver" => "search#compliment_receiver"
  match "/ck_likes/like_compliment_from_user_profile" => "ck_likes#like_compliment_from_user_profile",
        :as => :like_compliment_from_user_profile
  match "users/:id/dev_popup" => "users#dev_popup"
  match "users/:id/facebook" => "users#facebook", :as => :user_facebook
  match "users/:id/get_more_karma_live_records" => "users#get_more_karma_live_records",
        :as => :get_more_karma_live_records
  match "users/:id/my_updates" => "users#my_updates", :as => :my_updates
  match "users/:id/my_updates_all" => "users#my_updates_all", :as => :my_updates_all
  match "users/:id/professional_profile" => "users#professional_profile", 
        :as => :user_professional_profile
  match "users/:id/show_recognition_detail" => "users#show_recognition_detail", 
        :as => :show_recognition_detail
  match "users/:id/resend_new_account_confirmation" => "users#resend_new_account_confirmation",
        :as => :resend_new_account_confirmation
  match "users/:id/switch_accounts" => "users#switch_accounts", :as => :switch_accounts
  match "users/:id/edit_from_profile" => "users#edit_from_profile", :as => :edit_from_profile
  match "users/:id/upload_photo" => "users#upload_photo", :as => :upload_photo

  ## User Menu Routes
  match "users/:id/achievements" => "users#achievements", :as => :user_achievements
  match "users/:id/contacts" => "users#contacts", :as => :user_contacts
  match "users/:id/settings" => "users#settings", :as => :user_settings
  match "users/:id/privacy" => "users#privacy", :as => :user_privacy
  match "users/:id/employees" => "users#employees", :as => :user_employees
  match "users/:id/rewards" => "users#rewards", :as => :user_rewards
  match "users/:id/received_compliments" => "users#received_compliments", 
        :as => :user_received_compliments
  match "users/:id/sent_compliments" => "users#sent_compliments", 
        :as => :user_sent_compliments
  match "users/:id/social_profile" => "users#social_profile", :as => :user_social_profile

  match "users/:user_id/action_items/:id/pre_accept" => "action_items#pre_accept", 
        :as => :pre_accept_action_item
  match "users/:user_id/action_items/:id/accept" => "action_items#accept", 
        :as => :accept_action_item
  match "users/:user_id/action_items/:id/decline" => "action_items#decline", 
        :as => :decline_action_item
  match "users/:user_id/groups/update_super_group" => "groups#update_super_group", 
        :as => :update_super_group
  match "users/:user_id/user_emails/set_primary_email" => "user_emails#set_primary_email", 
        :as => :set_primary_email
  match "users/:user_id/user_emails/:id/update_unconfirmed_user_email" => 
          "user_emails#update_unconfirmed_user_email", 
        :as => :update_unconfirmed_user_email
  match "users/:user_id/user_emails/:id/resend_email_confirmation" => "user_emails#resend_email_confirmation",
        :as => :resend_email_confirmation

  match "users/:id/filter_contacts" => "users#filter_contacts", :as => :user_filter_contacts
  match "users/:user_id/contacts/add_remove_contact" => "contacts#add_remove_contact",
        :as => :add_remove_contact
  match "users/:user_id/contacts/create_contact" => "contacts#create", :as => :create_contact
  match "users/:user_id/contacts/:id/decline" => "contacts#decline",
        :as => :decline_contact
        

  # Metrics
  match "compliments/count" => "compliments#count"

  resources :follows
  resources :recognition_comments, :only => [:create]
  resources :ck_likes, :only => [:new, :create]
  resources :accomplishments
  resources :rewards  
  resources :relations
  resources :compliments
  resources :users do
    resources :action_items
    resources :contacts
    resources :groups
    resources :user_emails
  end
  resources :invitations
  resources :sessions, :only => [:new, :create, :destroy]
  resources :shells, :only => [:new, :create, :destroy]
  resources :password_resets
  resources :payments
  resources :experiences
  resources :company_department_users
  resources :company_departments
  resources :company_users
  resources :companies
  resources :recognitions

end

app/views/admin/header/_admin_menu.html.erb
<script>
	$(function() {
		Admin.init();
	});
</script>
<div id="admin-menu" class="drop-box">
	<div class="am-current-user">
		<ul>
			<li class="active-user no-hover">
				<div class="am-user-image">
					<%= image_tag(current_user.photo.url(:thumb)) %>
				</div>
				<% if current_user.is_a_company? %>
					<div class="am-user-info">
						<span class="am-name"><%= current_user.company.name %></span><br />
						<%= link_to "Account", '#', :class => 'ul_hover am-current-user-links' %>
					</div>
				<% else %>
					<div class="am-user-info">
						<span class="am-name"><%= current_user.first_last %></span><br />
						<span class="am-email"><%= current_user.try(:primary_email).try(:email) %></span><br />
						<div style="float:left;">
							<%= link_to "Account", 
													user_settings_path(:id => current_user.id), 
													:class => 'ul_hover am-current-user-links' %>
						</div>
						<div style="float:right;">
							<%= link_to "Privacy", 
													user_privacy_path(:id => current_user.id), 
													:class => 'ul_hover am-current-user-links' %>
						</div>
					</div>
				<% end %>
				<div class="clear"></div>
			</li>
		</ul>
		<div class="clear"></div>
	</div>
	<% if customer_admin_user? %>
		<ul>
			<% current_user.companies.each do |company| %>
				<% c_user = company.user %>
				<% if c_user.id != current_user.id %>
					<%= link_to switch_accounts_path(c_user), :class => 'company_profile' do %>
						<li>
							<div class="am-user-profile-image">
								<%= image_tag(c_user.photo.url(:thumb)) %>
							</div>
							<div class="am-user-profile-info">
								<%= company.name %>
							</div>
							<div class="clear"></div>
						</li>
					<% end %>
				<% end %>
			<% end %>
		</ul>
		<div class="clear"></div>
	<% elsif current_user_2 %>
		<ul>
			<%= link_to switch_accounts_path(current_user_2), :class => 'company_profile' do %>
				<li>
					<div class="am-user-profile-image">
						<%= image_tag(current_user_2.photo.url(:thumb)) %>
					</div>
					<div class="am-user-profile-info">
						<span class="am-name"><%= current_user_2.first_last %></span><br />
						<span class="am-email"><%= current_user_2.email %></span><br />
					</div>
					<div class="clear"></div>
				</li>
			<% end %>
		</ul>
		<div class="clear"></div>
	<% end %>
	<div class="am-button-container">
		<%= link_to 'Log Out', logout_path, :class => "button" %>
		<%= link_to 'Help', help_path, :class => "button" %>
		<div class="clear"></div>
	</div>
</div>