config/routes.rb
Ck::Application.routes.draw do

  root :to => "pages#index"
  
  match 'mailer(/:action(/:id(.:format)))' => 'mailer#:action'
  match "follows/multi_create_new" => "follows#multi_create", :as => :multi_create_follows
  match "follows/create_new" => "follows#create_new", :as => :create_follow
  match "/signup" => "users#new"
  match "/login" => "sessions#new", :as => "login"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/pricing" => "pages#pricing"
  match "/demo" => "pages#demo"
  match "/learn" => "pages#learn"
  match "/about" => "pages#about"
  match "/bad_words" => "pages#bad_words"
  match "/team" => "pages#team"
  match "/guidelines" => "pages#guidelines"
  match "/help" => "pages#help"
  match "/contact" => "pages#contact"
  match "/founder_signout" => "shells#destroy"
  match "/invite_coworkers" => "pages#invite_coworkers"
  match "/invite_others" => "pages#invite_others"
  match "/admin" => "admin#index", :as => :admin
  
  match "compliments/set_compliment_types" => "compliments#set_compliment_types"
  match "/email_api/new_account_confirmation" => "email_api#new_account_confirmation",
        :as => :new_account_confirmation
  match "/email_api/new_email_confirmation" => "email_api#new_email_confirmation",
        :as => :new_email_confirmation
  match "/email_api/invitation_acceptance" => "email_api#invitation_acceptance",
        :as => :invitation_acceptance
  match "/email_api/compliment_new" => "email_api#compliment_new",
        :as => :compliment_new_user
  match "/email_api/accept_compliment" => "email_api#accept_compliment",
        :as => :accept_compliment
  match "/email_api/decline_compliment" => "email_api#decline_compliment",
        :as => :decline_compliment
  match "/recognitions/:recognition_type_id/:recognition_id" => "recognitions#show", 
        :as => :show_recognition
  match "/relationships/:id/accept" => "relationships#accept", :as => :accept_relationship
  match "/relationships/:id/decline" => "relationships#decline", :as => :decline_relationship
  match "/rewards/add_to_cart" => "rewards#add_to_cart"
  match "/rewards/filter_rewards_results" => "rewards#filter_rewards_results"
  match "/rewards/cart" => "rewards#cart", :as => :cart
  match "/rewards/checkout" => "rewards#checkout", :as => :checkout
  match "/rewards/remove_from_cart" => "rewards#remove_from_cart", :as => :remove_from_cart
  match "/search/skills" => "search#skills"
  match "/search/site" => "search#site"
  match "/search/compliment_receiver" => "search#compliment_receiver"
  match "/ck_likes/like_compliment_from_user_profile" => "ck_likes#like_compliment_from_user_profile",
        :as => :like_compliment_from_user_profile
  match "users/:id/dev_popup" => "users#dev_popup"
  match "users/:id/facebook" => "users#facebook", :as => :user_facebook
  match "users/:id/get_more_karma_live_records" => "users#get_more_karma_live_records",
        :as => :get_more_karma_live_records
  match "users/:id/my_updates" => "users#my_updates", :as => :my_updates
  match "users/:id/my_updates_all" => "users#my_updates_all", :as => :my_updates_all
  match "users/:id/professional_profile" => "users#professional_profile", 
        :as => :user_professional_profile
  match "users/:id/show_recognition_detail" => "users#show_recognition_detail", 
        :as => :show_recognition_detail
  match "users/:id/resend_new_account_confirmation" => "users#resend_new_account_confirmation",
        :as => :resend_new_account_confirmation
  match "users/:id/switch_accounts" => "users#switch_accounts", :as => :switch_accounts
  match "users/:id/edit_from_profile" => "users#edit_from_profile", :as => :edit_from_profile
  match "users/:id/upload_photo" => "users#upload_photo", :as => :upload_photo

  ## User Menu Routes
  match "users/:id/achievements" => "users#achievements", :as => :user_achievements
  match "users/:id/contacts" => "users#contacts", :as => :user_contacts
  match "users/:id/settings" => "users#settings", :as => :user_settings
  match "users/:id/privacy" => "users#privacy", :as => :user_privacy
  match "users/:id/employees" => "users#employees", :as => :user_employees
  match "users/:id/rewards" => "users#rewards", :as => :user_rewards
  match "users/:id/received_compliments" => "users#received_compliments", 
        :as => :user_received_compliments
  match "users/:id/sent_compliments" => "users#sent_compliments", 
        :as => :user_sent_compliments
  match "users/:id/social_profile" => "users#social_profile", :as => :user_social_profile

  match "users/:user_id/action_items/:id/pre_accept" => "action_items#pre_accept", 
        :as => :pre_accept_action_item
  match "users/:user_id/action_items/:id/accept" => "action_items#accept", 
        :as => :accept_action_item
  match "users/:user_id/action_items/:id/decline" => "action_items#decline", 
        :as => :decline_action_item
  match "users/:user_id/groups/update_super_group" => "groups#update_super_group", 
        :as => :update_super_group
  match "users/:user_id/user_emails/set_primary_email" => "user_emails#set_primary_email", 
        :as => :set_primary_email
  match "users/:user_id/user_emails/:id/update_unconfirmed_user_email" => 
          "user_emails#update_unconfirmed_user_email", 
        :as => :update_unconfirmed_user_email
  match "users/:user_id/user_emails/:id/resend_email_confirmation" => "user_emails#resend_email_confirmation",
        :as => :resend_email_confirmation

  match "users/:id/filter_contacts" => "users#filter_contacts", :as => :user_filter_contacts
  match "users/:user_id/contacts/add_remove_contact" => "contacts#add_remove_contact",
        :as => :add_remove_contact
  match "users/:user_id/contacts/create_contact" => "contacts#create", :as => :create_contact
  match "users/:user_id/contacts/:id/decline" => "contacts#decline",
        :as => :decline_contact
        

  # Metrics
  match "compliments/count" => "compliments#count"

  resources :follows
  resources :recognition_comments, :only => [:create]
  resources :ck_likes, :only => [:new, :create]
  resources :accomplishments
  resources :rewards  
  resources :relations
  resources :compliments
  resources :users do
    resources :action_items
    resources :contacts
    resources :groups
    resources :user_emails
  end
  resources :invitations
  resources :sessions, :only => [:new, :create, :destroy]
  resources :shells, :only => [:new, :create, :destroy]
  resources :password_resets
  resources :payments
  resources :experiences
  resources :company_department_users
  resources :company_departments
  resources :company_users
  resources :companies
  resources :recognitions

end

app/helpers/users_helper.rb
module UsersHelper
  
  def set_active (active, arrow_number)
    return "active" if active == "slide#{arrow_number}"
    return "inactive"
  end
  
  def compliment_text(compliment)
    if compliment.nil? || compliment.comment.nil? || compliment.comment.blank?
      return "A comment was not entered for this compliment"
    else
      return compliment.comment
    end
  end

  def compliment_type(compliment)
    if compliment && compliment.compliment_type
      # html = '<span style="margin-right: 15px">'
      # html << compliment.compliment_type.name
      # html << '</span>'
      html = compliment.compliment_type.name
      return html.html_safe
    end
  end

  def compliment_skill(compliment)
    if compliment && compliment.skill_id
      skill = Skill.find_by_id(compliment.skill_id)
      return skill.name unless skill.blank?
    end
  end
  
  def compliment_status(compliment)
    if compliment.compliment_status
      return compliment.compliment_status.name
    else
      return "not specified"
    end
  end

  def account_status_display(confirmed, pending_items)
    return "" unless current_user?(@user)
    if confirmed
      if pending_items && pending_items.any?
        return "pending"
      end
    else
      return "not-confirmed"
    end
  end

  def pending_relationship_display(relationship)
    user = User.find(relationship.user_1_id)
    html = "Compliment from #{user.full_name}"
    html += " #{user.city}," if user.city
    html += " #{user.state_cd}" if user.state_cd
    html += " (#{user.email})"
    return html.html_safe
  end
  
  def tooltip(compliment)
    html = "sender: #{compliment.sender_email}\n"
    html += "receiver: #{compliment.receiver_email}\n"
    html += "status: #{compliment_status(compliment)}\n"
    html += "visibility: #{compliment.visibility.name}\n"
    sender = User.find_by_id(compliment.sender_user_id)
    if sender
      html += "sender status: #{sender.account_status.name}"
    else
      html += "sender status: Unregistered"
    end
    html += "\n"
    receiver = User.find_by_id(compliment.receiver_user_id)
    if receiver
      html += "receiver status: #{receiver.account_status.name}"
    else
      html += "receiver status: Unregistered"
    end
  end
  
  def get_content_for_recent_compliments(compliments_since_last_monday, index)
    if (index + 1 <= compliments_since_last_monday.size)
      receiver = compliments_since_last_monday[index].get_receiver
      if receiver
        html = link_to image_tag(receiver.photo.url(:mini), :width => "30"), 
                       receiver,
                       :title => "#{receiver.full_name}"
      else
        html = image_tag('/photos/mini/missing.png', :size => "30x30")
      end
    else
      html = (index + 1).to_s
    end
		return html
  end
  
  def get_likes_count(item_object_id, recognition_type_id)
    count = CkLike.get_count(item_object_id, recognition_type_id)
    return count_display(count)
  end

  def display_likes_header_count(count)
    if count.blank?
      return "No Likes at this time"
    elsif count == 1
      return "#{count} Like"
    else
      return "#{count} Likes"
    end
  end
  
  def get_comments_count(item_object, recognition_type_id)
    count = RecognitionComment.get_count(item_object.id, recognition_type_id)
    return count_display(count)
  end
  
  def get_like_status(recognition_id, recognition_type_id)
    return CkLike.UNLIKE unless current_user
    return CkLike.get_like_status(recognition_id, recognition_type_id, current_user.id)
  end

  def like_button(recognition_id, recognition_type_id)
    return if recognition_id.nil? || recognition_type_id.nil?
    status = get_like_status(recognition_id, recognition_type_id)
    logger.info("Like Status: #{status}")
    if status == CkLike.UNLIKE
      button_text = "Unlike"
      button_class = "unlike-button"
      # img = image_tag('buttons/Button_Unlike.png')
    else
      # button_text = '<font style="font-weight:bold;">♥</font>'
      button_text = "&hearts; Like"
      button_class = "like-button"
      # img = image_tag('buttons/Button_Like.png')
    end
    logger.info("Button Class: #{button_class}")
    # return link_to img, ck_likes_path(:recognition_type_id => recognition_type_id,
    #                                   :recognition_id => recognition_id,
    #                                   :count => @count,
    #                                   :user_id => current_user.id),
    #                     :method => :post,
    #                     :remote => true,
    #                     :id => "like-button"
    return link_to button_text.html_safe, ck_likes_path(:recognition_type_id => recognition_type_id,
                                      :recognition_id => recognition_id,
                                      :count => @count,
                                      :user_id => current_user.try(:id)),
                        :method => :post,
                        :remote => true,
                        :class => button_class
  end

  def likes_link(recognition_id, recognition_type_id)
    label = get_like_status(recognition_id, recognition_type_id)
    count = get_likes_count(recognition_id, recognition_type_id)
    return link_to "#{label} #{count}", 
                    ck_likes_path(:recognition_type_id => recognition_type_id,
                                  :recognition_id => recognition_id,
                                  :count => @count,
                                  :user_id => current_user.id),
                    :method => :post,
                    :remote => true
  end

  def comments_link(feed_item)
    label = "Comment"
    count = get_comments_count(feed_item.item_object, feed_item.item_type_id)
    return link_to "#{label} #{count}",
                   show_recognition_path(:recognition_type_id => feed_item.item_type_id,
                                                :recognition_id => feed_item.item_object.id),
                   :remote => true,
                   :id => "comment-count-#{feed_item.item_type_id}_#{feed_item.item_object.id}"
  end

  def compliments_link(feed_item, link_text)
    if feed_item && feed_item.item_type_id == @recognition_type_compliment_id
      if link_text =~ /Sender/
        sender = User.find_by_id(feed_item.item_object.sender_user_id)
        return "" if current_user?(sender)
        return link_to sender.full_name, 
                       new_compliment_path(:recipient_id => sender.id),
                                           :remote => true
      elsif link_text =~ /Receiver/
        receiver = User.find_by_id(feed_item.item_object.receiver_user_id)
        return "" if current_user?(receiver)
        return "Colleague" if receiver.blank?
        return link_to receiver.full_name,
                        new_compliment_path(:recipient_id => receiver.id),
                                            :remote => true
      else
        link_to link_text, new_compliment_path, :remote => true
      end
    elsif feed_item && feed_item.item_type_id == @recognition_type_reward_id
      if link_text =~ /Presenter/
        presenter = User.find(feed_item.item_object.presenter_id)
        return "" if current_user?(presenter)
        return link_to presenter.full_name, 
                       new_compliment_path(:recipient_id => presenter.id),
                                           :remote => true
      elsif link_text =~ /Receiver/
        receiver = User.find(feed_item.item_object.receiver_id)
        return "" if current_user?(receiver)
        return link_to receiver.full_name, 
                       new_compliment_path(:recipient_id => receiver.id),
                                           :remote => true
      else
        link_to link_text, new_compliment_path, :remote => true
      end
    else
      return link_to link_text, new_compliment_path(:recipient_id => feed_item.item_object.user_id),
                                                    :remote => true
    end
  end

  def compliment_button_medium(user=nil)
    # compliment_button(user, 'medium-button')
    compliment_button(user)
  end

  def compliment_button_large(user=nil)
    # compliment_button(user, 'large-button')
    compliment_button(user)
  end

  def compliment_button(user=nil, button_class=nil)
    if user && user.id == current_user.try(:id)
      return ""
    elsif user && user.id != current_user.try(:id)
      return link_to "Compliment", 
                     new_compliment_path(:recipient_id => user.id), 
                     :class => "compliment-button #{button_class}",
                     :remote => true
    else
      return link_to "Compliment", 
                     new_compliment_path, 
                     :class => "compliment-button #{button_class}",
                     :remote => true      
    end
  end

  def follows_button_medium(subject_user=nil)
    return "" if subject_user.nil?
    # follows_button(user.id, "medium-button")
    follows_button(subject_user.id)
  end

  def follows_button_large(subject_user=nil)
    return "" if subject_user.nil?
    # follows_button(user.id, "large-button")
    follows_button(subject_user.id)
  end

  def follows_button(subject_user_id=nil, button_size_class=nil)
    return "" if subject_user_id == current_user.id
    if subject_user_id
      button_class = "follow-button #{button_size_class}"
      button_text = "Follow"
      if follow_exists?(subject_user_id)
        button_class = "following-button #{button_size_class}"
        button_text = "Following"
      end
      return follows_button_link(subject_user_id, button_text, button_class)
    end
  end

  def follows_button_link(subject_user_id, button_text, button_class=nil)
    return link_to button_text, follows_path(:subject_user_id => subject_user_id,
                                         :follower_user_id => current_user.id),
                                :method => :post,
                                :class => button_class,

app/views/users/menu/_achievements.html.erb
<div id="user-achievements" class="right-two-thirds drop-box-white">
	<h1>Achievements</h1>
</div>

app/views/users/menu/_compliment_list.html.erb
<div id="user-profile">
	<div id="content-container" class="right-two-thirds drop-box-white clearfix">
		<div class="send-reward">
			<table id="compliment-display" class="tablesorter">
				<thead>
					<%
						header = "Sender"
						header = "Recipient" if sent_compliments
					%>
					<tr class="header">
						<th><div class="col3">Date</div></th>
						<th><div class="col2"><%= header %></div></th>
						<th><div class="col6">Skill</div></th>
						<th><div class="col3">Type</div></th>
						<th><div class="col3c">Status</div></th>
						<th><div class="col7c">Visibility</div></th>
					</tr>
				</thead>
				<tbody>
					<% unless compliments.blank? %>
						<% compliments.each_with_index do |compliment| %>
							<% 
								user_display = compliment.try(:sender).try(:first_last)
								if sent_compliments
									user_display = compliment.receiver_name
								end
								skill = Skill.find_by_id(compliment.skill_id)
							%>
							<tr>
								<td><%= date_time_format(compliment.created_at) %></td>
								<td><%= user_display %></td>
								<td><%= skill.name if skill %></td>
								<td><%= compliment.compliment_type.name if compliment.compliment_type %></td>
								<td class="centered"><%= compliment.compliment_status.name if compliment.compliment_status %></td>
								<td><%= compliment.visibility.name if compliment.visibility %></td>
							</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/menu/_contacts.html.erb
<div id="user-contacts" class="right-two-thirds drop-box-white">
	<div style="padding: 10px;">
		<h1 style="display: inline;">Contacts</h1>
		<div id="contact-list-header">
			<%= render :partial => 'contacts/list_header',
								 :locals => { :user_contacts_count => @user_contacts_count,
								 							:user => @user,
								 							:groups => @groups,
								 							:filter => @filter,
								 							:group_counts => @group_counts } %>
		</div>
		<div id="contact-list">
			<%= render :partial => 'contacts/list_with_picture', 
								 :locals => {:contacts => @contacts, 
								 						 :user => @user, 
								 						 :groups => @groups,
								 						 :filter_id => @filter} %>
		</div>
		<div class="clear"></div>
	</div>
</div>

app/views/users/menu/_employees.html.erb
<div id="user-profile">
	<div id="content-container">
		<div id="employee-list" class="right-two-thirds">
			<ul id="list-items">
				<% @count = @page * @per_page - @per_page %>
				<% if @results %>
					<% @results.each do |user| %>
						<% @count += 1 %>
						<%= link_to user do %>
							<li id="item_<%= @count %>" class="search-result">
								<div class="image" style="margin: 5px 0 0 0;">
									<%= image_tag(user.photo.url(:thumb)) %>
								</div>
								<div class="feed-item-center">
									<h1><%= user.full_name %></h1>
									<h2><%= location_display(user) %></h2>
								</div>
							</li>
						<% end %>
					<% end %>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/users/menu/_karma_live.html.erb
<div id="karma-live-updates" class="right-two-thirds">
	<ul id="feed-items">
		<%#= render 'users/panels/debug' %>
		<%= render 'users/panels/karma_live_updates' %>
	</ul>
	<div id="infinite-scroll-processing">
		Loading Records &nbsp; <%= image_tag('ajax-loader.gif') %>
		<div class="clear"></div>
	</div>
</div>

<script type="text/javascript">
	$(function() {
		UserProfile.infiniteScrolling();
	})
</script>

app/views/users/menu/_menu.html.erb
<script type="text/javascript">
	$(function() {
		UserMenu.init();
		$('#user-menu li').click(function(event) {
			// ComplimentUI.removeStickyCompliment();
		});
	});
</script>
<%
	individual_page = view_state(@user) == view_state_user_manager ||
									  view_state(@user) == view_state_user_visitor
	company_page = view_state(@user) == view_state_company_visitor ||
								 view_state(@user) == view_state_company_manager
	manager = view_state(@user) == view_state_user_manager ||
					  view_state(@user) == view_state_company_manager
	visitor = view_state(@user) == view_state_company_visitor ||
					  view_state(@user) == view_state_user_visitor
%>
<div id="user-menu" class="box-no-padding">
	<ul>
		<li id="menu-karma-live">
			<%= link_to 'Karma Activity', @user, :remote => true %>
		</li>
		<li id="menu-professional-profile">
			<%= link_to 'Professional Profile', user_professional_profile_path(@user), :remote => true %>
		</li>
		<% if individual_page %>
			<li id="menu-social-profile">
				<%= link_to 'Social Profile', user_social_profile_path(@user), :remote => true %>
			</li>
		<% end %>
		<% if manager %>
			<li id="menu-received-compliments">
				<%= link_to 'Received Compliments', user_received_compliments_path(@user), :remote => true %>
			</li>
		<% end %>
		<% if manager %>
			<li id="menu-sent-compliments">
				<%= link_to 'Sent Compliments', user_sent_compliments_path(@user), :remote => true %>
			</li>
		<% end %>
		<% if manager %>
			<li id="menu-contacts">
				<%= link_to 'Contacts', user_contacts_path(@user), :remote => true %>
			</li>
		<% end %>
		<% if @hide_me %>
			<li id="menu-achievements">
				<%= link_to 'Achievements', user_achievements_path(@user), :remote => true %>
			</li>
		<% end %>
		<% if company_page %>
			<li id="menu-employees">
				<%= link_to 'Employees', user_employees_path(@user), :remote => true %>
			</li>
		<% end %>
	</ul>
</div>

app/views/users/menu/_privacy.html.erb
<script>
	$(function() {
		$('li.user-group').each(function(){
			var contact = new Contact(this);
		});
	});
</script>
<div id="user-profile">
	<div id="user-overview" class="right-two-thirds drop-box-white clearfix">
		<div id="user-profile-details" class="first-row clearfix container">
			<h1>Privacy Settings</h1>
			<p><strong>Who can see my Profile and Activity </strong>
				(Compliments, Achievements, Rewards, etc.</p>
			<ul id="user-privacy">
				<% @groups.try(:each) do |g| %>
					<% next unless g.display? %>
					<li id="<%= g.id %>" class="user-group">
						<div class="group-info">
							<%= g.name %>
						</div>
						<div class="group-visibility">
							<div class="show-popup show-tag-groups">
								<div style="float: left; color:blue;">
									<div style="float: left; margin-right: 5px;">&#9660;</div>
									<div id="csv-list-groups" style="float: left;"><%= super_group_list(g) %></div>
									<div class="clear"></div>
								</div>
							</div>
						</div>
						<div class="hover-container">
						</div>
						<div class="popup">
							<%= render :partial => 'users/privacy/popup',
												 :locals => {:groups => @groups,
												 						 :subject_group => g} %>
 						</div>
						<div class="clear"></div>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/users/menu/_professional_profile.html.erb
<script>
	$(function() {
			UserProfile.stripeTable();
	})
</script>
<div id="user-profile">
	<div id="user-overview" class="right-two-thirds drop-box-white clearfix">
		<% if @valid_visitor %>
			<div id="user-profile-details" class="first-row clearfix container">
				<div class="personal-container clearfix">
					<div class="demographics-container">
						<div class="demographics">
							<div id="current-experience-container">
								<% unless company_user? || !current_user.confirmed? %>
									<%= render 'experiences/current_experience', :current_experience => @current_experience %>
								<% end %>
							</div>
							<%= render 'follows/follows_button', :user => @user %>
						</div>
					</div>
					<div class="rank-buttons">
						<div class="profile-rank-image">
							<%= complimenter_rank_image(@compliments_sent.to_i) %>
						</div>
						<div class="profile-rank-image">
							<%= rewarder_rank_image(@rewards_sent.to_i) %>
						</div>
					</div>
				</div>
				<%= render 'users/menu/profile/profile_stats', :type => "professional" %>
			</div>
			<%= render 'users/menu/profile/achievements', 
								 :compliments_received_by_skill => @compliments_received_by_skill %>
			<% unless @user_is_a_company %>
				<%= render 'users/menu/profile/experience.html.erb' %>
			<% end %>
		<% else %>
			<div style="padding: 20px;">
				<p style="font-size: 14px;"><%= @user.first_last %> is not sharing the Professional Profile</p>
			</div>
		<% end %>
	</div>
</div>

app/views/users/menu/_received_compliments.html.erb
<script type="text/javascript">
	$(function() {
		$('#compliment-display tr:nth-child(even)').addClass('alternate');
		$('#compliment_display').tablesorter();
	});
</script>
<%= render :partial => 'users/menu/compliment_list', 
					 :locals => {:sent_compliments => false,
					 						 :compliments => @compliments } %>

app/views/users/menu/_sent_compliments.html.erb
<script type="text/javascript">
	$(function() {
		$('#compliment-display tr:nth-child(even)').addClass('alternate');
		$('#compliment_display').tablesorter();
	});
</script>
<%= render :partial => 'users/menu/compliment_list', 
					 :locals => {:sent_compliments => true,
					 						 :compliments => @compliments } %>

app/views/users/menu/_settings.html.erb
<div id="user-profile">
	<div id="user-overview" class="right-two-thirds drop-box-white clearfix">
		<div id="user-profile-details" class="first-row clearfix container">
			<h1>Account Settings</h1>
			<ul id="account-settings">
				<li><%= link_to 'Privacy Settings', user_privacy_path(current_user) %></li>
				<li>
					<%= link_to 'Add/Manage Email Addresses', 
											user_user_emails_path(:user_id => @user.id), :remote => true %>
				</li>
			</ul>
			<% if view_state(@user) == view_state_company_manager %>
				<h2>Departments</h2>
				<% unless @departments.blank? %>
					<table>
						<tr>
							<th>Name</th>
							<th>Manager</th>
						</tr>
						<% @departments.each do |department| %>
							<tr>
								<td><%= department.name %></td>
								<td><%= department.manager %></td>
							</tr>
						<% end %>
					</table>
					<%= link_to 'New Department', new_company_department_path(:company_id => @company.id) %>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/menu/_social_profile.html.erb
<div id="user-profile">
	<div id="user-overview" class="right-two-thirds drop-box-white">
		<% if @valid_visitor %>
			<div id="user-profile-details" class="first-row clearfix container">
				<div class="personal-container clearfix">
					<div class="demographics-container">
						<div class="demographics">
							<%= render 'follows/follows_button', :user => @user %>
						</div>
					</div>
					<div class="rank-buttons">
						<div class="profile-rank-image">
							<%= complimenter_rank_image(@compliments_sent.to_i) %>
						</div>
						<div class="profile-rank-image">
							<%= rewarder_rank_image(@rewards_sent.to_i) %>
						</div>
					</div>
				</div>

				<%= render 'users/menu/profile/profile_stats', :type => "social" %>

			</div>
			<%= render 'users/menu/profile/achievements',
								 :compliments_received_by_skill => @compliments_received_by_skill %>
		<% else %>
			<div style="padding: 20px;">
				<p style="font-size: 14px;"><%= @user.first_last %> is not sharing the Social Profile</p>
			</div>
		<% end %>
	</div>
</div>