config/routes.rb
Ck::Application.routes.draw do

  root :to => "pages#index"
  
  match 'mailer(/:action(/:id(.:format)))' => 'mailer#:action'
  match "follows/multi_create_new" => "follows#multi_create", :as => :multi_create_follows
  match "follows/create_new" => "follows#create_new", :as => :create_follow
  match "/signup" => "users#new"
  match "/login" => "sessions#new", :as => "login"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/pricing" => "pages#pricing"
  match "/demo" => "pages#demo"
  match "/learn" => "pages#learn"
  match "/about" => "pages#about"
  match "/bad_words" => "pages#bad_words"
  match "/team" => "pages#team"
  match "/guidelines" => "pages#guidelines"
  match "/help" => "pages#help"
  match "/contact" => "pages#contact"
  match "/founder_signout" => "shells#destroy"
  match "/invite_coworkers" => "pages#invite_coworkers"
  match "/invite_others" => "pages#invite_others"
  match "/admin" => "admin#index", :as => :admin
  
  match "compliments/set_compliment_types" => "compliments#set_compliment_types"
  match "/email_api/new_account_confirmation" => "email_api#new_account_confirmation",
        :as => :new_account_confirmation
  match "/email_api/new_email_confirmation" => "email_api#new_email_confirmation",
        :as => :new_email_confirmation
  match "/email_api/invitation_acceptance" => "email_api#invitation_acceptance",
        :as => :invitation_acceptance
  match "/email_api/compliment_new" => "email_api#compliment_new",
        :as => :compliment_new_user
  match "/email_api/accept_compliment" => "email_api#accept_compliment",
        :as => :accept_compliment
  match "/email_api/decline_compliment" => "email_api#decline_compliment",
        :as => :decline_compliment
  match "/recognitions/:recognition_type_id/:recognition_id" => "recognitions#show", 
        :as => :show_recognition
  match "/relationships/:id/accept" => "relationships#accept", :as => :accept_relationship
  match "/relationships/:id/decline" => "relationships#decline", :as => :decline_relationship
  match "/rewards/add_to_cart" => "rewards#add_to_cart"
  match "/rewards/filter_rewards_results" => "rewards#filter_rewards_results"
  match "/rewards/cart" => "rewards#cart", :as => :cart
  match "/rewards/checkout" => "rewards#checkout", :as => :checkout
  match "/rewards/remove_from_cart" => "rewards#remove_from_cart", :as => :remove_from_cart
  match "/search/skills" => "search#skills"
  match "/search/site" => "search#site"
  match "/search/compliment_receiver" => "search#compliment_receiver"
  match "/ck_likes/like_compliment_from_user_profile" => "ck_likes#like_compliment_from_user_profile",
        :as => :like_compliment_from_user_profile
  match "users/:id/dev_popup" => "users#dev_popup"
  match "users/:id/facebook" => "users#facebook", :as => :user_facebook
  match "users/:id/get_more_karma_live_records" => "users#get_more_karma_live_records",
        :as => :get_more_karma_live_records
  match "users/:id/my_updates" => "users#my_updates", :as => :my_updates
  match "users/:id/my_updates_all" => "users#my_updates_all", :as => :my_updates_all
  match "users/:id/professional_profile" => "users#professional_profile", 
        :as => :user_professional_profile
  match "users/:id/show_recognition_detail" => "users#show_recognition_detail", 
        :as => :show_recognition_detail
  match "users/:id/resend_new_account_confirmation" => "users#resend_new_account_confirmation",
        :as => :resend_new_account_confirmation
  match "users/:id/switch_accounts" => "users#switch_accounts", :as => :switch_accounts
  match "users/:id/edit_from_profile" => "users#edit_from_profile", :as => :edit_from_profile
  match "users/:id/upload_photo" => "users#upload_photo", :as => :upload_photo

  ## User Menu Routes
  match "users/:id/achievements" => "users#achievements", :as => :user_achievements
  match "users/:id/contacts" => "users#contacts", :as => :user_contacts
  match "users/:id/settings" => "users#settings", :as => :user_settings
  match "users/:id/privacy" => "users#privacy", :as => :user_privacy
  match "users/:id/employees" => "users#employees", :as => :user_employees
  match "users/:id/rewards" => "users#rewards", :as => :user_rewards
  match "users/:id/received_compliments" => "users#received_compliments", 
        :as => :user_received_compliments
  match "users/:id/sent_compliments" => "users#sent_compliments", 
        :as => :user_sent_compliments
  match "users/:id/social_profile" => "users#social_profile", :as => :user_social_profile

  match "users/:user_id/action_items/:id/pre_accept" => "action_items#pre_accept", 
        :as => :pre_accept_action_item
  match "users/:user_id/action_items/:id/accept" => "action_items#accept", 
        :as => :accept_action_item
  match "users/:user_id/action_items/:id/decline" => "action_items#decline", 
        :as => :decline_action_item
  match "users/:user_id/groups/update_super_group" => "groups#update_super_group", 
        :as => :update_super_group
  match "users/:user_id/user_emails/set_primary_email" => "user_emails#set_primary_email", 
        :as => :set_primary_email
  match "users/:user_id/user_emails/:id/update_unconfirmed_user_email" => 
          "user_emails#update_unconfirmed_user_email", 
        :as => :update_unconfirmed_user_email
  match "users/:user_id/user_emails/:id/resend_email_confirmation" => "user_emails#resend_email_confirmation",
        :as => :resend_email_confirmation

  match "users/:id/filter_contacts" => "users#filter_contacts", :as => :user_filter_contacts
  match "users/:user_id/contacts/add_remove_contact" => "contacts#add_remove_contact",
        :as => :add_remove_contact
  match "users/:user_id/contacts/create_contact" => "contacts#create", :as => :create_contact
  match "users/:user_id/contacts/:id/decline" => "contacts#decline",
        :as => :decline_contact
        

  # Metrics
  match "compliments/count" => "compliments#count"

  resources :follows
  resources :recognition_comments, :only => [:create]
  resources :ck_likes, :only => [:new, :create]
  resources :accomplishments
  resources :rewards  
  resources :relations
  resources :compliments
  resources :users do
    resources :action_items
    resources :contacts
    resources :groups
    resources :user_emails
  end
  resources :invitations
  resources :sessions, :only => [:new, :create, :destroy]
  resources :shells, :only => [:new, :create, :destroy]
  resources :password_resets
  resources :payments
  resources :experiences
  resources :company_department_users
  resources :company_departments
  resources :company_users
  resources :companies
  resources :recognitions

end

app/models/action_item.rb
class ActionItem < ActiveRecord::Base
	belongs_to :action_item_type
	belongs_to :user
	belongs_to :originating_user, :class_name => "User", :foreign_key => 'originating_user_id'

	default_scope :order => 'created_at desc'

	def complete?
		return self.complete == "Y"
	end

	def set_complete
		update_attributes(:complete => "Y")
	end

	def self.incomplete_for_user(user=nil)
		return nil if user.blank?
		ActionItem.where('user_id = ? and complete <> ?', user.id, 'Y')
	end

	def self.create_from_compliment(compliment)
		return if compliment.blank? || compliment.receiver.blank? ||
							receiver_is_an_accepted_contact?(compliment)
		create(:user_id => compliment.receiver.id,
           :recognition_type_id => RecognitionType.COMPLIMENT.id,
           :recognition_id => compliment.id,
           :action_item_type_id => ActionItemType.Authorize_Contact.id,
           :originating_user_id => compliment.sender.id )
  end

  def self.retrieve_from_compliment(compliment)
  	return nil if compliment.blank?
  	ActionItem.where(:recognition_type_id => RecognitionType.COMPLIMENT,
  									 :recognition_id => compliment.id,
  									 :complete => 'N').first
  end

  def self.receiver_is_an_accepted_contact?(compliment)
  	contacts = compliment.sender.existing_contacts(compliment.receiver)
  	logger.info("Compliment Receiver: #{compliment.receiver.primary_email.email}")
  	c = contacts.collect{|x| x.group.name }
  	logger.info("New Action Item from compliment Contacts: #{c}")
  	if contacts.length > 0
  		contacts.each do |c|
  			return false if c.group.declined?
  		end
  		return true
		else
			return false
		end
  end

  def send_accept_notification
    UpdateHistory.Accepted_Compliment_Receiver(self)
  end

  def send_decline_notification
    UpdateHistory.Rejected_Compliment_Receiver(self)
  end

end

app/models/action_item_type.rb
class ActionItemType < ActiveRecord::Base
	has_many :action_items

	validates_uniqueness_of :name

	def self.Authorize_Contact
		find_by_name('Authorize Compliment')
	end
	
end

app/controllers/action_items_controller.rb
class ActionItemsController < ApplicationController
	before_filter :authenticate
	before_filter :correct_user
	before_filter :set_compliment_panel
  before_filter :get_confirmation_status, :except => [:new, :create]

	def index
		@action_items = ActionItem.incomplete_for_user(@user)
		@action_items_count = @action_items.count
	end

  def pre_accept
    @action_item = ActionItem.find(params[:id])
    @originator = User.find(params[:originator_user_id])
    @groups = @user.groups.where(:display_ind => 'Y')
  end

  def accept
    @action_item = ActionItem.find(params[:id])
    originator = User.find(params[:originator_user_id])
    groups = params[:groups]
    group_names = []
    logger.info("Groups #{groups}")
    groups.try(:each) do |k,v|
      logger.info("LOOP Groups #{k} => #{v}")
      if v.downcase == 'yes'
        logger.info("YES")
        Contact.create(:group_id => k, :user_id => originator.id)
        group_names << Group.find_by_id(k).try(:name)
      end
    end
    accept_relationship(originator)
    if @action_item.set_complete
      @action_item.send_accept_notification
      flash[:notice] = "#{originator.full_name} has been added as a contact in the following groups: 
                        #{group_names.join(', ')}"
      redirect_to @user
    end
  end

  def decline
    @action_item = ActionItem.find(params[:id])
    originator = User.find_by_id(params[:originator_user_id])
    decline_relationship(originator)
    logger.info("Action Item: #{@action_item.inspect}")
    if @action_item.recognition_type_id == RecognitionType.COMPLIMENT.id
      compliment = Compliment.find_by_id(@action_item.recognition_id)
      logger.info("Compliment: #{compliment.try(:inspect)}")
      compliment.try(:decline)
    end
    if @action_item.set_complete
      @action_item.send_decline_notification
      flash[:notice] = "You have declined the compliment from #{originator.try(:first_last)}"
      redirect_to @user
    end
  end

  def accept_relationship(originator)
    relationship = Relationship.get_relationship(originator, @user)
    relationship.accept_relationship unless relationship.blank?
  end

  def decline_relationship(originator)
    relationship = Relationship.get_relationship(originator, @user)
    relationship.decline_relationship unless relationship.blank?
  end

	private
    def authenticate
      store_location
      deny_access unless signed_in?
    end
    
    def correct_user
      @user = User.find(params[:user_id])
      good_user = current_user?(@user)
      redirect_to(root_path) unless good_user
    end

    def get_confirmation_status
      @confirmed = @user.blank? ? false: @user.confirmed?
    end
end

app/helpers/action_items_helper.rb
module ActionItemsHelper
end

app/views/action_items/_accept_decline_buttons.html.erb
<% originator_user_id = originator.blank? ? '' : originator.id %>
<div class="clear"></div>
<div style="margin: 10px 0 5px 0;">
	<div style="margin-left: 60px;">
		<div style="float-left;">
			<%= link_to 'Accept', 
									pre_accept_action_item_path(:user_id => user.id, 
																							:id => item.id, 
																							:originator_user_id => originator_user_id), 
									:id => item.id,
									:class => 'handle-action-item accept-action-item',
									:remote => true %>
		</div>
		<div style="float-left; margin-left: 100px;">
			<%= link_to 'Decline', 
									decline_action_item_path(:user_id => user.id, 
																					 :id => item.id, 
																					 :originator_user_id => originator_user_id),
									:class => 'handle-action-item decline-action-item' %>
		</div>
		<div class="clear"></div>
	</div>
</div>
<div class="clear"></div>

app/views/action_items/_action_item_indicator_time.html.erb
<div class="my-update-indicator-time clearfix">
	<div class="indicator-image">
		<%= action_item_image(item) %>
	</div>
	<div class="update-time">
		<%= timestamp(item.created_at) %>
	</div>
</div>

app/views/action_items/_action_items.html.erb
<div id="my-updates">
	<div id="my-updates-header">
		<h1 style="float: left; margin-left: 10px;">My Action Items</h1>
		<span class="my-notification-header_link">
			<%= link_to 'See All', user_action_items_path(user), :class => "ul_hover" %>
		</span>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
	<% if action_items && user.confirmed? %>
		<ul id="new-content">
			<% action_items.limit(5).each do |item| %>
				<% originator = item.originating_user %>
				<% if item.recognition_type_id.nil? || item.recognition_id.nil? %>
					<li class="clearfix my-updates-list" 
						  style="border-left: 1px solid #C9E6EE; margin-left: -1px">
						<%= link_to user_action_item_path(user, item) do %>
							<div class="my-update-all-item-image">
								<%= get_user_photo_thumb(item) %>
							</div>
							<div class="my-update-item-note">
								<p class="originator-note">
									<strong><%= get_update_user_full_name(item) %></strong> <%= item.note %>
								</p>
								<%= render 'my_updates/update_compliments_all', :item => item %>
							</div>
							<%= render 'action_items/action_item_indicator_time', :item => item %>
						<% end %>
						<%= render :partial => 'action_items/accept_decline_buttons', 
											 :locals => {:item => item, 
											 						 :user => user,
											 						 :originator => originator} %>
					</li>
				<% else %>
					<li class="clearfix my-updates-list" 
							style="border-left: 2px solid #DCF1EF; margin-left: -2px">

						<%= link_to show_recognition_path(:recognition_type_id => item.recognition_type_id, 
																							:recognition_id => item.recognition_id,
																							:update_history_id => nil),
																							:remote => true do %>
							<div class="my-update-all-item-image">
								<%= get_user_photo_thumb(item) %>
							</div>
							<div class="my-update-item-note clearfix">
								<p class="originator-note">
									<strong><%= get_update_user_full_name(item) %></strong> <%= item.note %>
								</p>
								<%= render 'my_updates/update_compliments_all', :item => item %>
							</div>
							<%= render 'action_items/action_item_indicator_time', :item => item %>
						<% end %>
						<%= render :partial => 'action_items/accept_decline_buttons', 
											 :locals => {:item => item, 
											 						 :user => user,
											 						 :originator => originator} %>
					</li>
				<% end %>
			<% end %>
		</ul>
	<% elsif !@user.confirmed? && !@my_update_items.blank? %>
		<div style="margin: 10px 0 0 10px;">
			<strong>
				Please confirm your account to view your action items (<%= @action_items_count %>)
			</strong>
		</div>
	<% end %>
</div>

app/views/action_items/_action_items_all.html.erb
<div id="my-updates">
	<div class="clear"></div>
	<% if action_items && user.confirmed? %>
		<ul id="new-content">
			<% action_items.limit(5).each do |item| %>
				<% originator = item.originating_user %>
				<% if item.recognition_type_id.nil? || item.recognition_id.nil? %>
					<%= link_to user_action_item_path(user, item) do %>
						<li class="clearfix my-updates-list" 
							  style="border-left: 1px solid #C9E6EE; margin-left: -1px">
							<div class="my-update-all-item-image">
								<%= get_user_photo_thumb(item) %>
							</div>
							<div class="my-update-item-note">
								<p class="originator-note">
									<strong><%= get_update_user_full_name(item) %></strong> <%= item.note %>
								</p>
								<%= render 'my_updates/update_compliments_all', :item => item %>
							</div>
							<%= render 'action_items/action_item_indicator_time', :item => item %>
						</li>
					<% end %>
				<% else %>
					<%= link_to show_recognition_path(:recognition_type_id => item.recognition_type_id, 
																						:recognition_id => item.recognition_id,
																						:update_history_id => nil),
																						:remote => true do %>
						<li class="clearfix my-updates-list" 
								style="border-left: 2px solid #DCF1EF; margin-left: -2px">
							<div class="my-update-all-item-image">
								<%= get_user_photo_thumb(item) %>
							</div>
							<div class="my-update-item-note clearfix">
								<p class="originator-note">
									<strong><%= get_update_user_full_name(item) %></strong> <%= item.note %>
								</p>
								<%= render 'my_updates/update_compliments_all', :item => item %>
							</div>
							<%= render 'action_items/action_item_indicator_time', :item => item %>
						</li>
					<% end %>
				<% end %>
			<% end %>
		</ul>
	<% elsif !@user.confirmed? && !@my_update_items.blank? %>
		<div style="margin: 10px 0 0 10px;">
			<strong>
				Please confirm your account to view your action items (<%= @action_items_count %>)
			</strong>
		</div>
	<% end %>
</div>

app/views/action_items/_action_items_indicator.html.erb
<% if current_user %>
	<% if @action_items_count && @action_items_count > 0 %>
		<%= link_to user_action_items_path(current_user), 
																			 :class => 'header-update-link', 
																			 :remote => true do %>
			<div class="header-updates clearfix">
				<div class="header-action-item-indicator"></div>
				<div id="update-history-count" class="header-update-count">
					<%= @action_items_count %>
				</div>
			</div>
		<% end %>
	<% else %>
		<%= link_to user_action_items_path(current_user),
																			 :class => 'header-update-link', 
																			 :remote => true do %>
			<div class="header-updates clearfix">
				<div class="header-action-item-indicator"></div>
				<div id="update-history-count"></div>
			</div>
		<% end %>
	<% end %>
<% end %>

app/views/action_items/_pre_accept.html.erb
<div class="contact-accept-form">
	<div id="my-updates-header">
		<h1 style="float: left;">What type of contact is <%= originator.full_name %></h1>
		<div class="clear"></div>
	</div>
	<%= form_tag accept_action_item_path(:user_id => user.id, :id => action_item.id) do %>
		<%= hidden_field_tag 'originator_user_id', originator.id %>
		<ul>
			<% groups.try(:each) do |group| %>
				<% unless group.declined? %>
					<li><%= check_box_tag "groups[#{group.id}]", 'yes', group.professional? %>
							<%= group.name %></li>
				<% end %>
			<% end %>
		</ul>
		<div>
			<button type=submit>Accept Contact</button>
		</div>
	<% end %>
</div>

app/views/action_items/index.html.erb
<%= content_for :javascript do %>
	<script type="text/javascript">
		$(function() {
			var flashMsg = "<%= flash[:error] %>";
			if(flashMsg.length > 0) {
				$('#field label').hide();
			}
			// MyUpdates.markAsRead();
		});
	</script>
<% end %>
<div id="user-profile">
	<div class="left-one-third">
		<%= render 'users/panels/user_profile_short', :flash => flash %>
	</div>
	<%= render 'compliments/new_compliment' %>
	<div id="karma-live-updates" class="right-two-thirds">
		<%= render :partial => 'action_items/action_items_all',
							 :locals => {:user => @user,
							 						 :action_items => @action_items,
							 						 :action_items_count => @action_items_count }  %>
	</div>
</div>

app/views/action_items/index.js.erb
UserProfile.reinitialize();
var view = '<%= j(render :partial => "action_items/action_items",
												 :locals => {:user => @user,
												 						 :action_items => @action_items,
												 						 :action_items_count => @action_items_count } ) %>';
ShowMyUpdateFancyBox.init(view);

app/views/action_items/pre_accept.js.erb
var view = '<%=j render :partial => "action_items/pre_accept",
												:locals => {:groups => @groups, 
																		:user => @user,
																		:action_item => @action_item,
																		:originator => @originator} %>'
$.fancybox(view, {
	beforeLoad: function() {
		$('body').addClass('lock-screen');
	},
	beforeClose: function() {
		$('body').removeClass('lock-screen');
	},
	minWidth: 450,
	minHeight: 50,
	// padding: 0,
	helpers: {
		overlay: {
			css: {
				'background': '#A7DBD8'
			}
		}
	}
});