config/routes.rb
Ck::Application.routes.draw do

  root :to => "pages#index"
  
  match 'mailer(/:action(/:id(.:format)))' => 'mailer#:action'
  match "follows/multi_create_new" => "follows#multi_create", :as => :multi_create_follows
  match "follows/create_new" => "follows#create_new", :as => :create_follow
  match "/signup" => "users#new"
  match "/login" => "sessions#new", :as => "login"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/pricing" => "pages#pricing"
  match "/demo" => "pages#demo"
  match "/learn" => "pages#learn"
  match "/about" => "pages#about"
  match "/bad_words" => "pages#bad_words"
  match "/team" => "pages#team"
  match "/guidelines" => "pages#guidelines"
  match "/help" => "pages#help"
  match "/contact" => "pages#contact"
  match "/founder_signout" => "shells#destroy"
  match "/invite_coworkers" => "pages#invite_coworkers"
  match "/invite_others" => "pages#invite_others"
  match "/admin" => "admin#index", :as => :admin
  
  match "compliments/set_compliment_types" => "compliments#set_compliment_types"
  match "/email_api/new_account_confirmation" => "email_api#new_account_confirmation",
        :as => :new_account_confirmation
  match "/email_api/new_email_confirmation" => "email_api#new_email_confirmation",
        :as => :new_email_confirmation
  match "/email_api/invitation_acceptance" => "email_api#invitation_acceptance",
        :as => :invitation_acceptance
  match "/email_api/compliment_new" => "email_api#compliment_new",
        :as => :compliment_new_user
  match "/email_api/accept_compliment" => "email_api#accept_compliment",
        :as => :accept_compliment
  match "/email_api/decline_compliment" => "email_api#decline_compliment",
        :as => :decline_compliment
  match "/recognitions/:recognition_type_id/:recognition_id" => "recognitions#show", 
        :as => :show_recognition
  match "/relationships/:id/accept" => "relationships#accept", :as => :accept_relationship
  match "/relationships/:id/decline" => "relationships#decline", :as => :decline_relationship
  match "/rewards/add_to_cart" => "rewards#add_to_cart"
  match "/rewards/filter_rewards_results" => "rewards#filter_rewards_results"
  match "/rewards/cart" => "rewards#cart", :as => :cart
  match "/rewards/checkout" => "rewards#checkout", :as => :checkout
  match "/rewards/remove_from_cart" => "rewards#remove_from_cart", :as => :remove_from_cart
  match "/search/skills" => "search#skills"
  match "/search/site" => "search#site"
  match "/search/compliment_receiver" => "search#compliment_receiver"
  match "/ck_likes/like_compliment_from_user_profile" => "ck_likes#like_compliment_from_user_profile",
        :as => :like_compliment_from_user_profile
  match "users/:id/dev_popup" => "users#dev_popup"
  match "users/:id/facebook" => "users#facebook", :as => :user_facebook
  match "users/:id/get_more_karma_live_records" => "users#get_more_karma_live_records",
        :as => :get_more_karma_live_records
  match "users/:id/my_updates" => "users#my_updates", :as => :my_updates
  match "users/:id/my_updates_all" => "users#my_updates_all", :as => :my_updates_all
  match "users/:id/professional_profile" => "users#professional_profile", 
        :as => :user_professional_profile
  match "users/:id/show_recognition_detail" => "users#show_recognition_detail", 
        :as => :show_recognition_detail
  match "users/:id/resend_new_account_confirmation" => "users#resend_new_account_confirmation",
        :as => :resend_new_account_confirmation
  match "users/:id/switch_accounts" => "users#switch_accounts", :as => :switch_accounts
  match "users/:id/edit_from_profile" => "users#edit_from_profile", :as => :edit_from_profile
  match "users/:id/upload_photo" => "users#upload_photo", :as => :upload_photo

  ## User Menu Routes
  match "users/:id/achievements" => "users#achievements", :as => :user_achievements
  match "users/:id/contacts" => "users#contacts", :as => :user_contacts
  match "users/:id/settings" => "users#settings", :as => :user_settings
  match "users/:id/privacy" => "users#privacy", :as => :user_privacy
  match "users/:id/employees" => "users#employees", :as => :user_employees
  match "users/:id/rewards" => "users#rewards", :as => :user_rewards
  match "users/:id/received_compliments" => "users#received_compliments", 
        :as => :user_received_compliments
  match "users/:id/sent_compliments" => "users#sent_compliments", 
        :as => :user_sent_compliments
  match "users/:id/social_profile" => "users#social_profile", :as => :user_social_profile

  match "users/:user_id/action_items/:id/pre_accept" => "action_items#pre_accept", 
        :as => :pre_accept_action_item
  match "users/:user_id/action_items/:id/accept" => "action_items#accept", 
        :as => :accept_action_item
  match "users/:user_id/action_items/:id/decline" => "action_items#decline", 
        :as => :decline_action_item
  match "users/:user_id/groups/update_super_group" => "groups#update_super_group", 
        :as => :update_super_group
  match "users/:user_id/user_emails/set_primary_email" => "user_emails#set_primary_email", 
        :as => :set_primary_email
  match "users/:user_id/user_emails/:id/update_unconfirmed_user_email" => 
          "user_emails#update_unconfirmed_user_email", 
        :as => :update_unconfirmed_user_email
  match "users/:user_id/user_emails/:id/resend_email_confirmation" => "user_emails#resend_email_confirmation",
        :as => :resend_email_confirmation

  match "users/:id/filter_contacts" => "users#filter_contacts", :as => :user_filter_contacts
  match "users/:user_id/contacts/add_remove_contact" => "contacts#add_remove_contact",
        :as => :add_remove_contact
  match "users/:user_id/contacts/create_contact" => "contacts#create", :as => :create_contact
  match "users/:user_id/contacts/:id/decline" => "contacts#decline",
        :as => :decline_contact
        

  # Metrics
  match "compliments/count" => "compliments#count"

  resources :follows
  resources :recognition_comments, :only => [:create]
  resources :ck_likes, :only => [:new, :create]
  resources :accomplishments
  resources :rewards  
  resources :relations
  resources :compliments
  resources :users do
    resources :action_items
    resources :contacts
    resources :groups
    resources :user_emails
  end
  resources :invitations
  resources :sessions, :only => [:new, :create, :destroy]
  resources :shells, :only => [:new, :create, :destroy]
  resources :password_resets
  resources :payments
  resources :experiences
  resources :company_department_users
  resources :company_departments
  resources :company_users
  resources :companies
  resources :recognitions

end

app/models/user_email.rb
class UserEmail < ActiveRecord::Base
	belongs_to :user

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates_presence_of :user_id
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }

  before_create :set_domain
  before_create :init_confirmed
  before_create :set_primary
  after_save :update_redis
  after_destroy :update_redis

  default_scope :order => 'primary_email DESC, confirmed DESC, email ASC'

  def is_primary?
  	self.primary_email == 'Y'
  end

  # def self.primary?
  #   where("primary_email = ?", 'Y')
  # end

  def is_confirmed?
    self.confirmed == 'Y'
  end
  
  def set_domain
  	return if self.email.blank?
  	return unless self.domain.blank?
    domain_array = self.email.split('@')
    self.domain = domain_array.last
  end

  def init_confirmed
  	self.confirmed = "N" if self.confirmed.blank?
  end

  def confirm_email
    update_attributes(:confirmed => 'Y')
  end

  def set_primary
    logger.info("Set Primary for Email #{self.email}")
  	return if self.user_id.blank?
  	addresses = User.find(self.user_id).email_addresses
  	if addresses.keep_if{ |a| a.is_primary? }.blank?
  		self.primary_email = "Y"
  	else
  		self.primary_email = "N"
  	end
  end

  def set_primary_override
    logger.info("Set Primary Override")
    current_primary_email = self.user.primary_email
    current_primary_email.update_attributes(:primary_email => "N")
  	self.update_attributes(:primary_email => "Y")
  end
  
  def compliment_cannot_be_to_self
    if(self.sender_email == self.receiver_email)
      errors.add(:receiver_email, 
                  "We think you are wonderful too but you cannot compliment yourself") 
    end
  end

  def update_redis
    u = self.user
    u.add_to_redis
  end

  def associate_compliments
    logger.info("User Email - Associate Compliments")
    Compliment.where(:receiver_email => self.email)
              .update_all(:receiver_user_id => user_id,
                          :compliment_status_id => ComplimentStatus.ACTIVE.id)
  end

  def disassociate_compliments
    Compliment.update_receiver_user_id(nil, self.email)
  end

  def send_email_confirmation
    generate_new_email_confirmation_token
    UserMailer.new_email_confirmation(self).deliver
  end

  def generate_new_email_confirmation_token
    generate_token(:new_email_confirmation_token)
    save!
  end

  def generate_token(column)
    begin
      logger.info("Generate Token: #{column}")
      self[column] = SecureRandom.urlsafe_base64
    end while UserEmail.exists?(column => self[column])
  end

end

app/controllers/user_emails_controller.rb
class UserEmailsController < ApplicationController
	before_filter :authenticate
	before_filter :get_email_addresses
	before_filter :correct_user

	def index
		@user_email = @user.email_addresses.build
		@source = params[:source]
	end

	def new
		@user_email = UserEmail.new
	end

	def create
		@user_email = UserEmail.new(params[:user_email])
		@user_email.user_id = current_user.id
		notice = "Your new email address has been added"
		if @user_email.save
			@user_email.associate_compliments
			@user_email.send_email_confirmation
			respond_to do |format|
				format.html { redirect_to current_user, :notice => notice }
				format.js { flash.now[:notice] = notice } #fall through to create.js.erb
			end
		else
			logger.info("Errors: #{@user_email.errors.messages}")
			respond_to do |format|
				format.html { render 'new' }
				format.js { 
					flash.now[:error] = error_display(@user_email)
					render 'error_display'
				}
			end
		end
	end

	# Only to be used by new users
	def update_unconfirmed_user_email
		new_email = params[:user_email][:email]
		@user_email = UserEmail.find(params[:id])
		notice = "Your email address has been changed.<br />
						  A confirmation message has been sent to your new email address".html_safe
		if @user_email.update_attributes(:email => new_email)
			@user.update_attributes(:email => new_email)
			@user.send_account_confirmation
			respond_to do |format|
				format.html { redirect_to current_user, :notice => notice }
				format.js { flash.now[:notice] = notice }
			end
		else
			logger.info("Errors: #{@user_email.errors.messages}")
			respond_to do |format|
				format.html { render 'new' }
				format.js { 
					flash.now[:error] = error_display(@user_email)
					render 'error_display'
				}
			end
		end
	end

	def resend_email_confirmation
		@user_email = UserEmail.find(params[:id])
		@user_email.send_email_confirmation
		notice = "Your email confirmation has been sent to #{@user_email.email}"
		respond_to do |format|
			format.html { redirect_to current_user, :notice => notice }
		  format.js { flash.now[:notice] = notice }
		end
	end

	def error_display(user_email)
		unless user_email.errors.blank?
			error_list = user_email.errors.messages.collect {|k,v| "#{k} #{v.join(',')}" }
			return error_list.join("\n")
		end
	end

	def set_primary_email
		@user_email = UserEmail.find_by_id(params[:id])
		@user_email.set_primary_override if @user_email
		get_email_addresses
		respond_to do |format|
			format.html { redirect_to current_user, :notice => 'Your primary email has been updated'}
			format.js { } #fall through
		end
	end

	def destroy
		@user_email = UserEmail.find(params[:id])
		unless @user_email.is_primary?
			@user_email.destroy
			respond_to do |format|
				format.html { redirect_to current_user }
				format.js {}
			end
		else
			flash.now[:error] = "You cannot delete your primary email address. 
											 Please assign a new primary email address before deleting this address"
			respond_to do |format|
				format.html {redirect_to current_user}
				format.js {render 'error_display'}
			end
		end
	end

  private
    def authenticate
      deny_access unless signed_in?
    end

    def get_email_addresses
    	@user_emails = current_user.email_addresses
    end

    def correct_user
      @user = User.find(params[:user_id])
      good_user = current_user?(@user)
      redirect_to(root_path) unless good_user
    end

end

app/helpers/user_emails_helper.rb
module UserEmailsHelper

	def email_status_class(user_email)
		if user_email.is_primary?
			return "primary"
		elsif !user_email.is_confirmed?
			return "unconfirmed"
		else
			return "non-primary"
		end
	end

	def email_primary_link(user_email)
		if !user_email.is_confirmed?
			return link_to "Send Confirmation Email", 
										 resend_email_confirmation_path(:user_id => current_user.id, :id => user_email.id),
										 :remote => true
		elsif user_email.is_primary?
			return "<span class='color: green;'>Primary email</span>".html_safe
		else
			return link_to 'Make Primary', 
										 set_primary_email_path(:user_id => current_user.id, :id => user_email.id), 
										 :remote => true
		end
	end

end

app/views/user_emails/_add_manage_emails.html.erb
<div id="user-information">
	<div class="header">
		<h2>Add/Manage Email Addresses</h2>
	</div>
	<div id="user-info-form-container" class="popup-form">
		<h1>Add an Email Address</h1>
		<p><strong>Please add at least 1 work email and 1 personal email.</strong> After adding the new email, go to that account and click the link in the confirmation email.</p>
		<br />
		<%= render 'inline_forms/add_email_address', :user_email => user_email %>
		<br />
		<h1>Choose your Primary Email Address</h1>
		<p>Click "Make primary" next to the address you want to use for ComplimentKarma emails. Email addresses must be confirmed before they can become primary.</p>
		<div class="clear"></div>
	</div>
	<div id="email-table">
		<%= render 'user_emails/email_table', :user_emails => @user_emails %>
	</div>

</div>

app/views/user_emails/_email_table.html.erb
<script>
	$(function() {
		$('#email-addresses tr:nth-child(odd)').addClass('alternate');
	});
</script>
<table id="email-addresses" class="email-addresses">
	<% user_emails.each do |ue| %>
		<tr>
			<td class="email-address <%= email_status_class(ue) %>"><%= ue.email %></td>
			<td class="primary-status"><%= email_primary_link(ue) %></td>
			<td class="remove-email">
				<%= link_to 'Remove', user_user_email_path(@user, ue), :method => :delete, :remote => true %>
			</td>
		</tr>
	<% end %>
</table>

app/views/user_emails/create.js.erb
var container = $('#email-table');
$('input#user_email_email').val('');
container.html('<%=j render "user_emails/email_table", :user_emails => @user_emails %>')

var container = $('#user-info-form-container');
var existingFlash = container.find('#flash');
if(existingFlash != null && existingFlash.length > 0) {
	container.remove(existingFlash);
}
container.prepend('<%=j render "shared/flash", :flash => flash %>');
$('#flash').slideDown();
CommonScripts.setCloseHandler();

app/views/user_emails/destroy.js.erb
var container = $('#email-table');
container.html('<%=j render "user_emails/email_table", :user_emails => @user_emails %>')

app/views/user_emails/error_display.js.erb
var container = $('#user-info-form-container');
var existingFlash = container.find('#flash');
if(existingFlash != null && existingFlash.length > 0) {
	container.remove(existingFlash);
}
container.prepend('<%=j render "shared/flash", :flash => flash %>');

$('#flash').slideDown();
CommonScripts.setCloseHandler();

app/views/user_emails/index.js.erb
var source = '<%= @source %>';
var userId = '<%= @user.id %>';
console.log(source);
var view = '<%= j(render :partial => "user_emails/add_manage_emails", 
										     :locals => {:user_emails => @user_emails, 
										 						     :user_email => @user_email,
										 						     :user => @user} ) %>';
var redirectView = '<%=j render(:partial => "users/fancyboxes/unconfirmed",
                                :locals => {:user => @user}) %>';
var host = 'http://www.complimentkarma.com/users'
<% if Rails.env.development? %>
  host = 'http://localhost:3000/users/'
<% end %>
var options = {
  view: view,
  source: source,
  userId: userId,
  redirectView: redirectView,
  redirectHost: host
};
console.log(options);
ShowFancybox.init(options);
InlineForms.init();

app/views/user_emails/resend_email_confirmation.js.erb
var container = $('#user-info-form-container');
var existingFlash = container.find('#flash');
if(existingFlash != null && existingFlash.length > 0) {
	container.remove(existingFlash);
}
container.prepend('<%=j render "shared/flash", :flash => flash %>');
$('#flash').slideDown();

app/views/user_emails/set_primary_email.js.erb
var container = $('#email-table');
container.html('<%=j render "user_emails/email_table", :user_emails => @user_emails %>')
var emailContainer = $('#header-email-container');
var primaryEmail = '<%=j @user_email.email %>'
emailContainer.html(primaryEmail + ' &#9660;');

app/views/user_emails/update_unconfirmed_user_email.js.erb
var container = $('#user-info-form-container');
var existingFlash = container.find('#flash');
if(existingFlash != null && existingFlash.length > 0) {
  container.remove(existingFlash);
}
container.prepend('<%=j render "shared/flash", :flash => flash %>');

$('#flash').slideDown();
CommonScripts.setCloseHandler();